# Generated by Django 5.2.12 on 2026-03-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_alter_task_additional_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('FE', 'Frontend'), ('BE', 'Backend'), ('UI', 'UI/UX'), ('DO', 'DevOps')], max_length=2, null=True),
        ),
    ]
